pop-os/cosmic-store

- i18n/ru/cosmic_store.ftl
- i18n/zh-cn/cosmic_store.ftl
Initial Russian and Chinese translations.
> Add Russian and Chinese i8n

- i18n/es/cosmic_store.ftl
- i18n/fr/cosmic_store.ftl
- i18n/it/cosmic_store.ftl
- i18n/ja/cosmic_store.ftl
- i18n/nl/cosmic_store.ftl
As far as actually continuing these in the future is concerned, Japanese will be my focus, not only because it is my major, but also due to the surprisingly low support of Japanese in the Linux world (e.g., there have been several times, especially on KDE, where a program will have better support in Catalan and Basque, minority languages of a country whose whole population is less than half of Japan's).
The other four languages will be much easy to find translators for in my opinion.
> Start 5 translations (Japanese, French, Spanish, Italian, Dutch)

- i18n/sv/cosmic_store.ftl
> Create cosmic_store.ftl - Add Swedish Translation

- i18n/pl/cosmic_store.ftl
Create basic Polish translation, there aren't any
> Create cosmic_store.ftl PL translation

- i18n/es/cosmic_store.ftl
- i18n/fr/cosmic_store.ftl
- i18n/it/cosmic_store.ftl
- i18n/ja/cosmic_store.ftl
- i18n/nl/cosmic_store.ftl
By the way, are the categories in the Nav Pages supposed to be imperatives (e.g. "Develop!") or infinitives (e.g. "to develop")?  I'm asking because in other languages, imperatives and infinitives can be easier to tell apart («¡Desarrolle!» v.s. «desarrollar» in Spanish) so some context to help translators understand the feel of the new Cosmic Store would be nice.
> Update translations for Dutch, French, Italian, Spanish, and Japanese

- i18n/pl/cosmic_store.ftl
> Update cosmic_store.ftl PL translation

- i18n/de/cosmic_store.ftl
> i18n(de): Add translation

- i18n/pt-BR/cosmic_store.ftl
- Line 47 removed due to duplicity
- Translation of the Release notes section
> i18n(pt-BR) - Updating translation

- i18n/ru/cosmic_store.ftl
Add release notes strings, improve a few existing strings.
> i18n(ru): Update Russian translation

- Cargo.lock
- Cargo.toml
- src/localize.rs
- src/main.rs
> Replaced unmaintained lexical-sort with ICU

- i18n/uk/cosmic_store.ftl
Minor improvement to translation consistency with other COSMIC apps
> Update Ukrainian translation

- i18n/fr/cosmic_store.ftl
Hello,
This commit updates the french translations. Notable changes include:
- latest-version = Dernière version
- no-description = Aucune description disponible.
Other translations remain unchanged.
Best regards,
Roxfr
> Updated french translations for Cosmic Store

- src/main.rs
Closes: #130
Congrats on the successful launch, fellow Cosmonauts! :partying_face: :tada: :milky_way:
> improv: Cycle screenshots

- i18n/zh-CN/cosmic_store.ftl
- i18n/zh-TW/cosmic_store.ftl
> Add zh-TW and update zh-CN translations 

- src/main.rs
Fixes #148.
Possibly not the best way to to this, but it seems to work.
> Fix app open button

- Cargo.lock
- src/main.rs
This matches the search button to other header bar buttons.
> Make search button padding fixed

- i18n/pl/cosmic_store.ftl
Added Details, app urls and applies change to branding
> Update cosmic_store.ftl PL Translation Details Branding

- Cargo.lock
- Cargo.toml
> chore: update libcosmic

- Cargo.lock
- src/main.rs
Draft because clicking the search button causes problems
```
thread 'main' panicked at /home/jeremy/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/c70e536/iced/widget/src/container.rs:362:42:
called `Option::unwrap()` on a `None` value
```
> Update to new libcosmic/iced

- i18n/he/cosmic_store.ftl
Full Hebrew translation, I also want to check if RTL is working correctly, thanks!
> i18n(he): add Hebrew translation

- i18n/nl/cosmic_store.ftl
I spotted some minor spelling issues. I've dyslexia myself, so I didn't spot them earlier.  ;-) 
With regards
> improve & check for spelling the Dutch translation

- i18n/da/cosmic_store.ftl
I have translated the Cosmic Store into danish and would like to contribute it to the project.
> i18n(dk): Add Danish translation

- res/com.system76.CosmicStore.desktop
Due to changed branding i renamed the name.
> Update com.system76.CosmicStore.desktop PL metadata

- src/main.rs
Closes: #291
With downloads:
Without downloads:
> Don't show monthly downloads if 0

- i18n/pl/cosmic_store.ftl
> Update cosmic_store.ftl PL Translation applets

- Cargo.lock
- Cargo.toml
- debian/postinst
- debian/prerem
- i18n/en/cosmic_store.ftl
- src/backend/mod.rs
- src/backend/packagekit.rs
- src/gstreamer.rs
- src/main.rs
This allows us to replace the ancient sessioninstaller.
> WIP: gstreamer codec installation

- i18n/pl/cosmic_store.ftl
> Update cosmic_store.ftl PL Translation Codec Close
